import type { Metadata } from 'next';
import Header from '@/widgets/header/ui/index';
import './globals.css';
import ThemeRegistry from './theme-registry';

import { Inter } from 'next/font/google';
import localFont from 'next/font/local';

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

const ttFirs = localFont({
  src: [
    {
      path: '../shared/assets/fonts/TTFirsNeue-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../shared/assets/fonts/TTFirsNeue-DemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-tt-firs', // 👈 ключевая штука
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} ${ttFirs.variable}`}
    >
      <head>
        {/* Material Symbols */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </head>

      <body className="min-h-full flex flex-col">
        <ThemeRegistry>
          <Header />
          <main className="w-2xl m-auto">
            {children}
          </main>
        </ThemeRegistry>
      </body>
    </html>
  );
}