import type { Metadata } from 'next';
import Header from '@/widgets/header/ui/index';
import './globals.css';
import ThemeRegistry from './theme-registry';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Подключаем иконки Material Symbols */}
        <link 
          rel="stylesheet" 
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" 
        />
      </head>
      <body className="min-h-full flex flex-col">
        <Header />
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}