import type { Metadata } from 'next';
import Header from '@/widgets/header/ui/index';
import './globals.css';
import ThemeRegistry from './theme-registry';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <Header />
          <main className='w-2xl m-auto'>
            <ThemeRegistry>
              {children}
            </ThemeRegistry>
          </main>
      </body>
    </html>
  );
}
